### ISSUE TITLE
QG训练营网络组第三周周记

### ISSUE THREAD

**Issue by wzc2016** [wzc2016/wengzechuan#5]
# QG训练营网络组第三周周记

## 生活随记
> 主要精力：
> 1.了解并学习了一些Java知识
> 2.继续学习加强前端的布局设计
> 3.网上看了一遍css，jquery《JavaScript DOM 编程艺术》的大部分
> 4.模仿做了百度的首页

## 学习情况
> 1.因为之前基本没接触过java，这周就看了一下视频，主要就是一些概念的东西，像基础语法，对象，类，异常，多态这些
> 2.网上找了固态布局，流动布局，响应式布局的介绍并了解学习了一下，主要是position和float的布局知识
> 3.学习了一下css3，主要是动画，转换和过渡
> 4.看了jquery，主要是jquery效果，jquery Html
> 5.主要了解了js的DOM方面的知识

## 一周终结
> 1.基本每天除了正常上课，其他时间都在学习相关知识吧
> 2.前端的js，css3，jquery有开始学

## 存在问题
> 1.我的C语言链表学的不好，还有java之前是基本没学过的，没能完成作业
> 2.学习效率不高，怀疑自己智商ㄒoㄒ)特别在时间安排上

## 下周规划

> 1尽量学点Java
> 2.把《JavaScript DOM 编程艺术》看完
> 3.学好网页的动画效果
> 4.准备高数期中考
> 5.背下周要听写的一个月英语单词

**Comment by ArtemisZ** [comment]
学习注意效率和时间，时间和效率有时候是不成正比的哦 ^-^，要学好C语言的链表果然还是要好好学一下指针和结构体，这两个很重要哦，特别是指针，特别多坑。
