### ISSUE TITLE
QG第三周笔记心得

### ISSUE THREAD

**Issue by wzc2016** [wzc2016/wengzechuan#6]
#  QG第三周笔记心得

## 上课
>1.编程范式::是某种编程语言典型的编程风格或者说是编程方式,是学习任何一门编程语言时要理解的重要术语。
> 常见编程范式：
> a.声明式编程：只要我们说出自己想要什么内容，然后机器自己去思考完成

> b.过程式编程:就是你想好算法的步骤，然后严格按照步骤一步步来编写程序，前面没有编好，就不能编后面的。

> c.面向对象编程:建立将计算建立在独立的对象相互作用之上。每个对象都是自身内部的状态

> d.文学式编程:使用日常的语言表达自己的逻辑。操作符由编程人员自己定义，组成了过在基本编程语言之上的“元语言”。(未来语言)

>2.面向对象
>三大特性：
>a. 封装：把对象的所有信息和方法都集中在一起。
>b.继承：
- 传递性：
- 清晰性：
- 可复用：
- 易维护:
- 单继承：

>c.多态：

> ps:继承是多态的基础。多态是继承的目的。
> ps:做一个有思想的和自己个性的程序员。

## 前端
> 1.display 是CSS中最重要的用于控制布局的属性。每个元素都有一个默认的 display 值，这与元素的类型有关。对于大多数元素它们的默认值通常是 block 或 inline 。一个 block 元素通常被叫做块级元素。一个 inline 元素通常被叫做行内元素。
> ps: display主要值：block, inline, none, inline-block
> 
>  2.设置块级元素的 width 可以阻止它从左到右撑满容器。然后可以设置左右外边距为 auto 来使其水平居中。
>  
>  3.inline-block 来布局需注意：
>  a.vertical-align 属性会影响到 inline-block 元素，我们可能会把它的值设置为 top 。
>  b.需要设置每一列的宽度
>  c.如果HTML源代码中元素之间有空格，那么列与列之间会产生空隙
>  
>  4.text-align和 margin区别：
>  a..text-align:center 设置文本或img标签等一些内联对象（或与之类似的元素）的居
>  b.margin:0 auto 设置块元素（或与之类似的元素）的居中。
>  
>  5.代码书写要规范化，如：
>  a 不要漏了双引号
>  b 在网页的表现上尽量用css样式来写，不要以HTML的特殊符号来实现样式
>  c 统一id或class命名方式
>  d 注意css属性书写顺序：位置属性(position, top, right, z­index, display, float等) —大小(width, height, padding, margin)—文字系列(font, line­height, letter­spacing,color— text­align等)­背景(background, border等)—其他(animation, transition等)

> 6.css3可以实现很多动画效果，不是说非得用到js。

> 7.jQuery 是一个 JavaScript 库,极大地简化了 JavaScript 编程。

**Comment by ArtemisZ** [comment]
师弟，不要太专注于前端，也要学一下后台哦，一个优秀的程序员要什么方面都多涉及，然后专精于一个方向。建议学一下Java。
